<a href="https://colab.research.google.com/github/petermesy/Machine-Learning-ML/blob/main/Prepare_Your_Data_For_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

7.4 Standardize Data
 Standardization is a useful technique to transform attributes with a Gaussian distribution and
 di ering means and standard deviations to a standard Gaussian distribution with a mean of
 0 and a standard deviation of 1. It is most suitable for techniques that assume a Gaussian
 distribution in the input variables and work better with rescaled data, such as linear regression,
 logistic regression and linear discriminate analysis. You can standardize data using scikit-learn
 with the StandardScaler class3.

In [20]:
from sklearn.preprocessing import StandardScaler
from pandas import read_csv
from numpy import set_printoptions

filename = '/content/indian.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

# Load the dataset and ensure the first row is treated as headers
dataframe = read_csv(filename, names=names, header=0)


In [21]:
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [22]:
dataframe=dataframe.dropna()
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [23]:
 array = dataframe.values
 # Ensure all columns are numeric
dataframe = dataframe.apply(pd.to_numeric, errors='coerce')

# Drop rows with missing values (if any)
dataframe = dataframe.dropna()
 # separate array into input and output components
 X = array[:,0:8]
 Y = array[:,8]
 scaler = StandardScaler().fit(X)
 rescaledX = scaler.transform(X)
 # summarize transformed data
 set_printoptions(precision=3)
 print(rescaledX[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


Normalize Data:
Normalizing in scikit-learn refers to rescaling each observation (row) to have a length of 1 (called
 a unit norm or a vector with the length of 1 in linear algebra)

```
# This is formatted as code
```



In [24]:
from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(X)
normalizedX=scaler.transform(X)
set_printoptions(precision=3)
print(normalizedX[0:5,:])

[[0.034 0.828 0.403 0.196 0.    0.188 0.004 0.28 ]
 [0.008 0.716 0.556 0.244 0.    0.224 0.003 0.261]
 [0.04  0.924 0.323 0.    0.    0.118 0.003 0.162]
 [0.007 0.588 0.436 0.152 0.622 0.186 0.001 0.139]
 [0.    0.596 0.174 0.152 0.731 0.188 0.01  0.144]]


 Binarize Data (Make Binary)
 You can transform your data using a binary threshold. All values above the threshold are
 marked 1 and all equal to or below are marked as 0. This is called binarizing your data or
 thresholding your data. It can be useful when you have probabilities that you want to make crisp
 values. It is also useful when feature engineering and you want to add new features that indicate
 something meaningful. You can create new binary attributes in Python using scikit-learn with
 the Binarizer class5.

In [27]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX=binarizer.transform(X)
set_printoptions(precision=3)
print(binaryX[0:5,:])


[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]
